# Generated by Django 2.2.13 on 2020-07-11 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='Injury_Illeness',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incident',
            name='date',
            field=models.DateField(default='2000-10-20'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incident',
            name='description',
            field=models.TextField(default='None'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incident',
            name='environmental_Incident',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incident',
            name='immediate_Action',
            field=models.TextField(default='None'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incident',
            name='incident_Location',
            field=models.TextField(default='office'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incident',
            name='location',
            field=models.CharField(default='Corporate Headoffice', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incident',
            name='property_damage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incident',
            name='reported_by',
            field=models.CharField(default='User', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incident',
            name='severity',
            field=models.CharField(default='low', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incident',
            name='suspected_Cause',
            field=models.TextField(default='None'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incident',
            name='time',
            field=models.TimeField(default='20:30'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incident',
            name='vehicle',
            field=models.BooleanField(default=False),
        ),
    ]
